### ISSUE TITLE
Reading analog inputs

### ISSUE THREAD

**Issue by David-OConnor** [rust-embedded/rust-spidev#22]
I'm looking for advice on reading analog inputs, fed through an ADC, then spi to rust-spidev.

I adapted the home page code, and am able to get a reading from the first analog input using tweaked `full-duplex` code. The half duplex code is outputting all 0s.

```rust
pub fn read_light(spi: &mut Spidev) -> io::Result<f32> {
    let tx_buf = [0x01, 0x02, 0x03, 0x04, 0x05];
    let mut rx_buf = [0; 5];
    {
        let mut transfer = SpidevTransfer::read_write(&tx_buf, &mut rx_buf);
        spi.transfer(&mut transfer)?;
    }

    let score = 
        // rx_buf[4] as u32
        rx_buf[3] as u32
        + rx_buf[2] as u32 * 256_u32
        + rx_buf[1] as u32* 256_u32.pow(2);

    // val is the portion of the maximum score we could get using the bits included above.
    let val = score as f32 / 256_f32.powi(3);
    Ok(calibration::map_light(val))
}
```

1: What determines the length of tx_buf to use? From experimenting, it seems that the left bits are weighted more heavily than the rights, ie if there's very low input voltage, maybe the 4th bit goes up from 0. When it hits 256, it goes back to zero, and the bit to the left goes up. How should you map analog voltage to SPI bits?

2: How can you differentiate different inputs? When I connect a second analog input (channel 2 on the ADC), the bits all are dramatically lower, and I'm not sure how to differentiate the devices.

I appologize if this is more of an ADC than `spidev` question.

**Comment by ryankurte** [comment]
hiya, you may be interested in [rust-embedded/embedded-hal](https://github.com/rust-embedded/embedded-hal) which provides more general SPI (and other) interfaces, and [rust-embedded/linux-embedded-hal ](https://github.com/rust-embedded/linux-embedded-hal) which provides implementations of these for linux, we would _generally_ recommend using these abstractions rather than spidev directly.

the rest of these questions depend on your ADC (and to some extent an understanding SPI interfaces), you might find [this](https://pramode.in/2018/02/24/an-introduction-to-writing-embedded-hal-based-drivers-in-rust/) blog post about an SPI ADC in rust useful, and it might be worth checking if there is already a [driver](https://github.com/rust-embedded/awesome-embedded-rust#driver-crates) for your adc, but other than that you're going to need to read up on SPI and the datasheet for the ADC you are using.

i'm going to close this as unrelated to spidev, if you have other embedded questions feel free to drop by the [matrix](https://matrix.to/#/#rust-embedded:matrix.org) chat, good luck!
